import { StyleSheet, Dimensions } from 'react-native';
import { colors, typography, spacing, fontFamily } from '../theme/theme';

const { width: W } = Dimensions.get('window');

export const loginScreenStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  keyboardAvoid: { flex: 1 },
  /** Matches header so the rounded card “bites” into blue, not white */
  loginScroll: { flex: 1, backgroundColor: colors.primary },
  loginScrollContent: {
    flexGrow: 1,
  },
  header: {
    backgroundColor: colors.primary,
    paddingVertical: spacing.xxxl,
    paddingHorizontal: spacing.xxxl,
    minHeight: 280,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  geo: {
    position: 'absolute',
    width: W * 1.6,
    height: 200,
    borderRadius: 2,
  },
  geo1: { backgroundColor: colors.primaryDark, opacity: 0.35, transform: [{ rotate: '-25deg' }], top: -80, left: -W * 0.5 },
  geo2: { backgroundColor: colors.primaryDark, opacity: 0.25, transform: [{ rotate: '20deg' }], top: 0, right: -W * 0.6 },
  geo3: { backgroundColor: colors.primaryDark, opacity: 0.2, transform: [{ rotate: '-35deg' }], bottom: -50, left: -W * 0.3 },
  geo4: { backgroundColor: colors.primaryDark, opacity: 0.15, transform: [{ rotate: '30deg' }], bottom: -30, right: -W * 0.4 },
  appName: { ...typography.h1, color: colors.white, fontSize: 36 },
  tagline: { ...typography.subtitle, color: colors.white, fontSize: 17, marginTop: spacing.md, opacity: 0.96 },
  /** Overlaps header; large radius reads clearly on all phones */
  card: {
    flexGrow: 1,
    backgroundColor: colors.card,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    marginTop: -28,
    paddingTop: spacing.xxl + 4,
    paddingHorizontal: spacing.xxxl,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 10,
  },
  welcome: { ...typography.h2, color: colors.text.primary },
  subWelcome: { ...typography.subtitle, color: colors.text.secondary, marginTop: spacing.sm, marginBottom: spacing.xxl },
  label: { ...typography.label, color: colors.text.label, marginBottom: spacing.sm },
  labelRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: spacing.xl, marginBottom: spacing.sm },
  forgot: { ...typography.link, color: colors.text.link },
  input: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBg,
    borderRadius: 12,
    paddingHorizontal: spacing.lg,
    height: 52,
  },
  inputIcon: { marginRight: spacing.md },
  inputField: { flex: 1, fontFamily: fontFamily.regular, fontSize: 16, color: colors.text.primary, paddingVertical: 0 },
  inputFieldPw: { paddingRight: spacing.sm },
  eyeBtn: { padding: spacing.sm },
  signInBtn: {
    backgroundColor: colors.primary,
    borderRadius: 27,
    height: 54,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: spacing.xxl,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  signInText: { ...typography.button, color: colors.white },
  footer: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginTop: 32, flexWrap: 'wrap' },
  /** Two footer lines: centred as a group, prompts + links left-aligned with each other */
  footerStack: { width: '100%', marginTop: 32, alignItems: 'center' },
  footerStackInner: { alignItems: 'flex-start' },
  footerRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: spacing.md },
  footerRowGap: { marginTop: spacing.lg },
  footerPrompt: { ...typography.caption, color: colors.text.label },
  footerLink: { ...typography.linkBold, color: colors.text.link },
  legal: { fontFamily: fontFamily.regular, fontSize: 11, color: colors.text.secondary, textAlign: 'center', marginTop: 24, paddingHorizontal: 24, opacity: 0.9 },
  forgotModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    paddingHorizontal: spacing.xxxl,
  },
  forgotModalCard: {
    backgroundColor: colors.card,
    borderRadius: 24,
    padding: spacing.xxl,
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 12,
  },
  forgotModalHeader: { flexDirection: 'row', justifyContent: 'flex-end', marginBottom: spacing.sm },
  forgotModalCloseBtn: { padding: spacing.sm, marginRight: -spacing.sm, marginTop: -spacing.sm },
  forgotModalIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(0,86,210,0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: spacing.lg,
  },
  forgotModalTitle: { ...typography.h2, fontSize: 22, color: colors.text.primary, textAlign: 'center', marginBottom: spacing.md },
  forgotModalBody: {
    ...typography.subtitle,
    fontSize: 15,
    lineHeight: 22,
    color: colors.text.secondary,
    textAlign: 'center',
    marginBottom: spacing.xl,
  },
  forgotModalHint: {
    fontFamily: fontFamily.regular,
    fontSize: 13,
    lineHeight: 19,
    color: colors.text.secondary,
    textAlign: 'center',
    marginBottom: spacing.lg,
    paddingHorizontal: spacing.sm,
  },
  forgotModalBtnSecondary: {
    marginTop: spacing.lg,
    paddingVertical: spacing.md,
    alignItems: 'center',
  },
  forgotModalBtnSecondaryText: { ...typography.link, color: colors.text.secondary, fontSize: 15 },
  forgotModalSuccessIcon: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#D1FAE5',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: spacing.lg,
  },
});
