import { StyleSheet, Dimensions } from 'react-native';
import { colors, typography, spacing, fontFamily } from '../theme/theme';

const { width: W } = Dimensions.get('window');

// ─── Login Screen ─────────────────────────────────────────────────────────
export const loginScreenStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  header: {
    backgroundColor: colors.primary,
    paddingVertical: spacing.xxxl,
    paddingHorizontal: spacing.xxxl,
    height: '40%',
    minHeight: 260,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  geo: {
    position: 'absolute',
    width: W * 1.6,
    height: 200,
    borderRadius: 2,
  },
  geo1: { backgroundColor: colors.primaryDark, opacity: 0.35, transform: [{ rotate: '-25deg' }], top: -80, left: -W * 0.5 },
  geo2: { backgroundColor: colors.primaryDark, opacity: 0.25, transform: [{ rotate: '20deg' }], top: 0, right: -W * 0.6 },
  geo3: { backgroundColor: colors.primaryDark, opacity: 0.2, transform: [{ rotate: '-35deg' }], bottom: -50, left: -W * 0.3 },
  geo4: { backgroundColor: colors.primaryDark, opacity: 0.15, transform: [{ rotate: '30deg' }], bottom: -30, right: -W * 0.4 },
  appName: { ...typography.h1, color: colors.white, fontSize: 36 },
  tagline: { ...typography.subtitle, color: colors.white, fontSize: 17, marginTop: spacing.md, opacity: 0.96 },
  card: {
    flex: 1,
    backgroundColor: colors.card,
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    marginTop: -24,
    paddingTop: spacing.xxl,
    paddingHorizontal: spacing.xxxl,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
    elevation: 8,
  },
  welcome: { ...typography.h2, color: colors.text.primary },
  subWelcome: { ...typography.subtitle, color: colors.text.secondary, marginTop: spacing.sm, marginBottom: spacing.xxl },
  label: { ...typography.label, color: colors.text.label, marginBottom: spacing.sm },
  labelRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: spacing.xl, marginBottom: spacing.sm },
  forgot: { ...typography.link, color: colors.text.link },
  input: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBg,
    borderRadius: 12,
    paddingHorizontal: spacing.lg,
    height: 52,
  },
  inputIcon: { marginRight: spacing.md },
  inputField: { flex: 1, fontFamily: fontFamily.regular, fontSize: 16, color: colors.text.primary, paddingVertical: 0 },
  inputFieldPw: { paddingRight: spacing.sm },
  eyeBtn: { padding: spacing.sm },
  signInBtn: {
    backgroundColor: colors.primary,
    borderRadius: 27,
    height: 54,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: spacing.xxl,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  signInText: { ...typography.button, color: colors.white },
  footer: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginTop: 32, flexWrap: 'wrap' },
  footerPrompt: { ...typography.caption, color: colors.text.label },
  footerLink: { ...typography.linkBold, color: colors.text.link },
  legal: { fontFamily: fontFamily.regular, fontSize: 11, color: colors.text.secondary, textAlign: 'center', marginTop: 24, paddingHorizontal: 24, opacity: 0.9 },
  bottom: { height: 28, backgroundColor: colors.background },
});

// ─── Create Account / Complete Profile Screen ───────────────────────────────
const profileBlue = '#0056D2';
export const createAccountScreenStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F5F6F8' },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    paddingHorizontal: spacing.xxxl,
    paddingVertical: spacing.lg,
    paddingTop: 0,
  },
  backBtn: { padding: spacing.sm, marginLeft: -spacing.sm },
  topBarTitle: { fontFamily: fontFamily.bold, fontSize: 20, color: profileBlue, marginLeft: spacing.md },
  progressSection: { paddingHorizontal: spacing.xxxl, paddingTop: spacing.xl },
  stepRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  stepText: { fontFamily: fontFamily.bold, fontSize: 11, color: profileBlue, letterSpacing: 0.5 },
  stepLabel: { fontFamily: fontFamily.regular, fontSize: 13, color: colors.text.secondary },
  progressBarBg: {
    height: 4,
    backgroundColor: '#E5E7EB',
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressBarFill: { height: '100%', width: '25%', backgroundColor: profileBlue, borderRadius: 2 },
  content: { flex: 1, paddingHorizontal: spacing.xxxl, paddingTop: spacing.xxl },
  /** Spacing before Full Legal Name when company picker is shown (step 1 only) */
  step1CompanyPickerWrap: { marginBottom: spacing.xl },
  title: { fontFamily: fontFamily.bold, fontSize: 26, color: colors.text.primary },
  subtitle: { fontFamily: fontFamily.regular, fontSize: 15, color: colors.text.secondary, marginTop: spacing.md, marginBottom: spacing.xxl, lineHeight: 22 },
  photoSection: { alignItems: 'center', marginBottom: spacing.xxl },
  photoWrapper: { position: 'relative', marginBottom: 0 },
  photoCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#E5E7EB',
  },
  photoAddBtn: {
    position: 'absolute',
    bottom: -4,
    right: -4,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: profileBlue,
    justifyContent: 'center',
    alignItems: 'center',
  },
  uploadLabel: { fontFamily: fontFamily.bold, fontSize: 15, color: profileBlue, marginTop: spacing.md },
  fieldLabel: { fontFamily: fontFamily.bold, fontSize: 14, color: profileBlue, marginBottom: spacing.sm },
  fieldHint: { fontFamily: fontFamily.regular, fontSize: 12, color: colors.text.secondary, marginBottom: spacing.sm },
  sexRow: { flexDirection: 'row', gap: spacing.lg },
  sexOption: {
    flex: 1,
    height: 52,
    borderRadius: 14,
    backgroundColor: colors.inputBg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sexOptionActive: { backgroundColor: profileBlue },
  sexOptionText: { fontFamily: fontFamily.regular, fontSize: 16, color: colors.text.primary },
  sexOptionTextActive: { color: colors.white, fontFamily: fontFamily.semiBold },
  daysRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  dayChip: {
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: 12,
    backgroundColor: colors.inputBg,
  },
  dayChipActive: { backgroundColor: profileBlue },
  dayChipText: { fontFamily: fontFamily.regular, fontSize: 14, color: colors.text.primary },
  dayChipTextActive: { color: colors.white, fontFamily: fontFamily.semiBold },
  idDocSection: { marginTop: spacing.xxl },
  idDocCard: {
    backgroundColor: colors.inputBg,
    borderRadius: 14,
    padding: spacing.lg,
    marginBottom: spacing.lg,
  },
  idDocCardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.md },
  idDocCardLabel: { fontFamily: fontFamily.semiBold, fontSize: 13, color: profileBlue },
  idDocRemoveBtn: { padding: spacing.xs },
  idDocUploadArea: {
    height: 120,
    borderRadius: 12,
    backgroundColor: colors.white,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#9CA3AF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  idDocUploadAreaFilled: { borderStyle: 'solid', borderColor: profileBlue },
  idDocUploadText: { fontFamily: fontFamily.regular, fontSize: 13, color: '#6B7280', marginTop: spacing.sm },
  idDocImage: { width: '100%', height: '100%', borderRadius: 10 },
  idDocAddBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: 12,
    backgroundColor: colors.inputBg,
    alignSelf: 'flex-start',
    marginTop: spacing.sm,
    gap: spacing.sm,
  },
  idDocAddBtnText: { fontFamily: fontFamily.semiBold, fontSize: 14, color: profileBlue },
  idDocMinHint: { fontFamily: fontFamily.regular, fontSize: 12, color: '#6B7280', marginTop: spacing.sm },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', padding: spacing.xxxl },
  modalContent: { backgroundColor: colors.white, borderRadius: 16, padding: spacing.lg },
  modalOption: { paddingVertical: spacing.lg, borderBottomWidth: 1, borderBottomColor: '#E5E7EB' },
  modalOptionLast: { borderBottomWidth: 0 },
  modalOptionText: { fontFamily: fontFamily.regular, fontSize: 16, color: colors.text.primary },
  input: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBg,
    borderRadius: 14,
    paddingHorizontal: spacing.lg,
    height: 52,
  },
  inputField: { flex: 1, fontFamily: fontFamily.regular, fontSize: 16, color: colors.text.primary, paddingVertical: 0 },
  inputMultiline: { minHeight: 80, alignItems: 'flex-start' },
  inputFieldMultiline: { minHeight: 76, textAlignVertical: 'top', paddingTop: spacing.lg },
  inputIconRight: { marginLeft: spacing.sm },
  saveBtn: {
    flexDirection: 'row',
    backgroundColor: profileBlue,
    borderRadius: 27,
    height: 54,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: spacing.xxl,
    marginBottom: spacing.xxxl,
    gap: spacing.sm,
  },
  saveBtnText: { fontFamily: fontFamily.bold, fontSize: 17, color: colors.white },
  // Success modal
  successModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.xxxl,
  },
  successModalCard: {
    backgroundColor: colors.white,
    borderRadius: 24,
    padding: spacing.xxl,
    alignItems: 'center',
    width: '100%',
    maxWidth: 340,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 12,
  },
  successIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#D1FAE5',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  successModalTitle: { fontFamily: fontFamily.bold, fontSize: 22, color: colors.text.primary, textAlign: 'center', marginBottom: spacing.md },
  successModalMessage: { fontFamily: fontFamily.regular, fontSize: 15, color: colors.text.secondary, textAlign: 'center', lineHeight: 24, marginBottom: spacing.xxl },
  successModalBtn: {
    backgroundColor: profileBlue,
    borderRadius: 14,
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.xxl * 2,
    alignSelf: 'stretch',
    alignItems: 'center',
  },
  successModalBtnText: { fontFamily: fontFamily.semiBold, fontSize: 16, color: colors.white },
  addressSuggestWrap: { position: 'relative', zIndex: 10, marginBottom: spacing.xs },
  addressSuggestDropdown: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: '100%',
    marginTop: spacing.sm,
    maxHeight: 220,
    backgroundColor: colors.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    zIndex: 100,
    elevation: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
  },
  addressSuggestScroll: { maxHeight: 220 },
  addressSuggestRow: {
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  addressSuggestRowLast: { borderBottomWidth: 0 },
  addressSuggestText: { fontFamily: fontFamily.regular, fontSize: 14, color: colors.text.primary, lineHeight: 20 },
  addressSuggestLoadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
  },
  addressSuggestLoadingText: { fontFamily: fontFamily.regular, fontSize: 13, color: colors.text.secondary },
  addressSuggestHint: {
    fontFamily: fontFamily.regular,
    fontSize: 11,
    color: colors.text.secondary,
    marginTop: spacing.xs,
    marginBottom: spacing.sm,
  },
});

// ─── Dashboard Screen ─────────────────────────────────────────────────────
export const dashboardStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F0F2F5' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.xxxl,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xl,
    backgroundColor: '#FFFFFF',
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 6,
  },
  profileAvatarWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#E8EEF5',
    padding: 2,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(0,61,122,0.15)',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
  },
  profileAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#E8EEF5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 22,
    color: colors.primary,
    marginLeft: spacing.lg,
    flex: 1,
    letterSpacing: -0.3,
  },
  bellBtn: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(0,61,122,0.08)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0,61,122,0.08)',
  },
  bellBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#EF4444',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  greetingCard: {
    marginHorizontal: spacing.xxxl,
    marginTop: spacing.lg,
    marginBottom: spacing.lg,
    backgroundColor: colors.white,
    borderRadius: 20,
    padding: spacing.xl,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.03)',
  },
  greetingText: { fontFamily: fontFamily.regular, fontSize: 14, color: colors.text.secondary },
  userName: { fontFamily: fontFamily.bold, fontSize: 24, color: colors.text.primary, marginTop: spacing.xs },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: spacing.xxxl,
    paddingTop: spacing.sm,
    paddingBottom: 120,
  },
  scrollView: { flex: 1 },
  content: { flex: 1, paddingHorizontal: spacing.xxxl, paddingTop: spacing.sm },
  clockInCard: {
    backgroundColor: colors.primary,
    borderRadius: 28,
    padding: spacing.xxl,
    alignItems: 'center',
    overflow: 'hidden',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 12,
  },
  clockInGeo: {
    position: 'absolute',
    width: W * 1.2,
    height: 180,
    borderRadius: 4,
  },
  clockInGeo1: { backgroundColor: colors.primaryDark, opacity: 0.25, transform: [{ rotate: '-20deg' }], top: -60, right: -W * 0.4 },
  clockInGeo2: { backgroundColor: colors.primaryDark, opacity: 0.15, transform: [{ rotate: '25deg' }], bottom: -40, left: -W * 0.5 },
  statusLabel: { fontFamily: fontFamily.bold, fontSize: 11, letterSpacing: 1.2, color: 'rgba(255,255,255,0.85)', marginBottom: spacing.sm },
  statusRow: { flexDirection: 'row', alignItems: 'center', marginBottom: spacing.xl },
  statusDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#EF4444', marginRight: spacing.sm },
  statusDotActive: { backgroundColor: '#22C55E' },
  statusText: { fontFamily: fontFamily.semiBold, fontSize: 15, color: colors.white },
  clockInBtn: {
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.xl,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  clockInBtnIcon: { marginBottom: spacing.sm },
  clockInBtnText: { fontFamily: fontFamily.bold, fontSize: 17, color: colors.primary },
  shiftPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.22)',
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.xxl,
    borderRadius: 24,
    gap: spacing.md,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
  },
  shiftPillText: { fontFamily: fontFamily.medium, fontSize: 15, color: colors.white },
  locationCard: {
    marginTop: spacing.xxl,
    backgroundColor: colors.white,
    borderRadius: 20,
    padding: spacing.xl,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.04)',
  },
  locationCardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: spacing.md,
    marginBottom: spacing.md,
  },
  locationHeading: { fontFamily: fontFamily.bold, fontSize: 17, color: colors.text.primary, flex: 1, flexShrink: 1 },
  locationShortName: {
    fontFamily: fontFamily.semiBold,
    fontSize: 16,
    color: colors.text.primary,
    lineHeight: 22,
    marginBottom: spacing.sm,
  },
  locationAddress: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.text.secondary,
    lineHeight: 22,
    width: '100%',
  },
  locationCoordsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  locationCoordsText: { fontFamily: fontFamily.regular, fontSize: 12, color: colors.text.secondary },
  locationMapTouchable: {
    marginTop: spacing.lg,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#E5E7EB',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.06)',
  },
  locationMapImageWrap: { position: 'relative', width: '100%' },
  locationMapImage: { width: '100%', height: 200 },
  locationMapLoadingBox: {
    height: 200,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#EEF2F7',
  },
  locationMapLoadingHint: {
    fontFamily: fontFamily.regular,
    fontSize: 13,
    color: colors.text.secondary,
    marginTop: spacing.md,
  },
  locationMapPinOverlay: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginLeft: -18,
    marginTop: -36,
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  locationMapFallback: {
    height: 200,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#EEF2F7',
    paddingHorizontal: spacing.lg,
  },
  locationMapFallbackText: {
    fontFamily: fontFamily.medium,
    fontSize: 14,
    color: colors.text.secondary,
    textAlign: 'center',
    marginTop: spacing.sm,
  },
  locationMapKeyHint: {
    fontFamily: fontFamily.regular,
    fontSize: 13,
    color: colors.text.secondary,
    lineHeight: 20,
    marginTop: spacing.sm,
    paddingHorizontal: spacing.sm,
  },
  locationMapKeyHintBold: {
    fontFamily: fontFamily.semiBold,
    fontSize: 13,
    color: colors.text.primary,
  },
  locationMapHint: {
    fontFamily: fontFamily.regular,
    fontSize: 12,
    color: colors.text.secondary,
    marginTop: spacing.sm,
    textAlign: 'center',
  },
  locationMapHintBelow: {
    fontFamily: fontFamily.regular,
    fontSize: 12,
    color: colors.text.secondary,
    textAlign: 'center',
    paddingVertical: spacing.sm,
  },
  locationMapAttribution: {
    fontFamily: fontFamily.regular,
    fontSize: 11,
    color: '#9CA3AF',
    textAlign: 'center',
    marginTop: spacing.sm,
  },
  locationErrorText: { color: '#EF4444' },
  locationRefreshRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.lg,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  inZoneBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#D1FAE5',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: 20,
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: 'rgba(5,150,105,0.2)',
  },
  outZoneBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF3C7',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: 20,
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: 'rgba(245,158,11,0.3)',
  },
  inZoneText: { fontFamily: fontFamily.semiBold, fontSize: 14, color: '#059669' },
  outZoneText: { fontFamily: fontFamily.semiBold, fontSize: 14, color: '#D97706' },
  locationRefreshBtn: { padding: spacing.sm },
  locationOpenSettingsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: colors.primary,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: 12,
    marginTop: spacing.md,
    gap: spacing.sm,
  },
  locationOpenSettingsText: { fontFamily: fontFamily.semiBold, fontSize: 14, color: colors.white },
});

// ─── Tasks Screen ───────────────────────────────────────────────────────────
const taskBlue = '#004C99';
export const tasksStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F0F2F5' },
  scrollView: { flex: 1 },
  scrollContent: { paddingBottom: 120 },
  sectionTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 20,
    color: colors.text.primary,
    marginHorizontal: spacing.xxxl,
    marginTop: spacing.lg,
    letterSpacing: -0.3,
  },
  sectionSubtitle: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.text.secondary,
    marginHorizontal: spacing.xxxl,
    marginTop: spacing.xs,
    marginBottom: spacing.md,
    lineHeight: 20,
  },
  filterRow: {
    flexDirection: 'row',
    paddingHorizontal: spacing.xxxl,
    gap: spacing.sm,
    marginBottom: spacing.lg,
  },
  filterChip: {
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    borderRadius: 20,
    backgroundColor: colors.inputBg,
  },
  filterChipActive: {
    backgroundColor: taskBlue,
  },
  filterChipText: {
    fontFamily: fontFamily.semiBold,
    fontSize: 13,
    color: colors.text.secondary,
  },
  filterChipTextActive: {
    color: colors.white,
  },
  taskCard: {
    marginHorizontal: spacing.xxxl,
    marginBottom: spacing.md,
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: spacing.lg,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.04)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  taskCardDone: { opacity: 0.72 },
  priorityBar: { width: 4, borderRadius: 2, alignSelf: 'stretch', minHeight: 48 },
  priorityHigh: { backgroundColor: '#DC2626' },
  priorityMedium: { backgroundColor: '#D97706' },
  priorityLow: { backgroundColor: '#94A3B8' },
  taskBody: { flex: 1 },
  taskTitle: {
    fontFamily: fontFamily.semiBold,
    fontSize: 16,
    color: colors.text.primary,
    lineHeight: 22,
  },
  taskTitleDone: { textDecorationLine: 'line-through', color: colors.text.secondary },
  taskDesc: {
    fontFamily: fontFamily.regular,
    fontSize: 13,
    color: colors.text.secondary,
    marginTop: spacing.xs,
    lineHeight: 19,
  },
  taskMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacing.md,
    marginTop: spacing.md,
  },
  taskMetaItem: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  taskMetaText: { fontFamily: fontFamily.regular, fontSize: 12, color: colors.text.secondary },
  taskBadge: {
    alignSelf: 'flex-start',
    marginTop: spacing.sm,
    paddingVertical: 4,
    paddingHorizontal: spacing.sm,
    borderRadius: 8,
    backgroundColor: '#F1F5F9',
  },
  taskBadgeText: { fontFamily: fontFamily.semiBold, fontSize: 11, color: taskBlue, textTransform: 'uppercase' },
  checkBtn: { padding: spacing.xs, marginTop: -spacing.xs },
  emptyState: {
    marginHorizontal: spacing.xxxl,
    paddingVertical: spacing.xxl * 2,
    alignItems: 'center',
  },
  emptyTitle: {
    fontFamily: fontFamily.semiBold,
    fontSize: 16,
    color: colors.text.secondary,
    marginTop: spacing.lg,
    textAlign: 'center',
  },
  emptyHint: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.text.secondary,
    marginTop: spacing.sm,
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: spacing.xl,
  },
});

// ─── Chat / AI Assistant Screen ─────────────────────────────────────────────
const chatBlue = '#004C99';
export const chatStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F0F2F5' },
  keyboardFill: { flex: 1 },
  listHeaderWrap: {
    paddingTop: spacing.lg,
    marginBottom: spacing.sm,
  },
  assistantBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    gap: spacing.sm,
    marginBottom: spacing.lg,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    backgroundColor: 'rgba(0,76,153,0.08)',
    borderRadius: 20,
  },
  assistantBadgeText: {
    fontFamily: fontFamily.semiBold,
    fontSize: 12,
    color: chatBlue,
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  faqSectionLabel: {
    fontFamily: fontFamily.bold,
    fontSize: 11,
    letterSpacing: 0.8,
    color: colors.text.secondary,
    marginBottom: spacing.sm,
    textTransform: 'uppercase',
  },
  faqGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: spacing.sm,
    marginBottom: spacing.xl,
  },
  faqChip: {
    width: '48%',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
    borderRadius: 14,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
  },
  faqChipText: {
    fontFamily: fontFamily.medium,
    fontSize: 13,
    color: chatBlue,
    textAlign: 'center',
  },
  messagesList: { flex: 1 },
  messagesContent: {
    paddingHorizontal: spacing.xxxl,
    paddingTop: spacing.md,
    paddingBottom: spacing.xl,
  },
  messageRow: { marginBottom: spacing.md, maxWidth: '92%' as const },
  messageRowAssistant: { alignSelf: 'flex-start' },
  messageRowUser: { alignSelf: 'flex-end' },
  bubbleAssistant: {
    backgroundColor: colors.white,
    borderRadius: 16,
    borderBottomLeftRadius: 4,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.06)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  bubbleUser: {
    backgroundColor: chatBlue,
    borderRadius: 16,
    borderBottomRightRadius: 4,
    padding: spacing.lg,
  },
  bubbleTextAssistant: {
    fontFamily: fontFamily.regular,
    fontSize: 15,
    color: colors.text.primary,
    lineHeight: 22,
  },
  bubbleTextUser: {
    fontFamily: fontFamily.regular,
    fontSize: 15,
    color: colors.white,
    lineHeight: 22,
  },
  bubbleMeta: {
    fontFamily: fontFamily.regular,
    fontSize: 11,
    color: colors.text.secondary,
    marginTop: spacing.sm,
  },
  inputBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingHorizontal: spacing.xxxl,
    paddingTop: spacing.lg,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    gap: spacing.sm,
    zIndex: 50,
    elevation: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  inputField: {
    flex: 1,
    minHeight: 44,
    maxHeight: 120,
    fontFamily: fontFamily.regular,
    fontSize: 16,
    color: colors.text.primary,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    backgroundColor: colors.inputBg,
    borderRadius: 22,
  },
  sendBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: chatBlue,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 2,
  },
  sendBtnDisabled: { backgroundColor: '#CBD5E1' },
  placeholderBanner: {
    marginBottom: spacing.lg,
    padding: spacing.lg,
    backgroundColor: '#FEF3C7',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(245,158,11,0.35)',
  },
  placeholderBannerText: {
    fontFamily: fontFamily.regular,
    fontSize: 12,
    color: '#92400E',
    lineHeight: 18,
    textAlign: 'center',
  },
});
