import { StyleSheet, Dimensions, Platform } from 'react-native';
import { colors, typography, spacing, fontFamily } from '../theme/theme';

const { width: W } = Dimensions.get('window');

// ─── Login Screen ─────────────────────────────────────────────────────────
export const loginScreenStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  keyboardAvoid: { flex: 1 },
  /** Matches header so the rounded card “bites” into blue, not white */
  loginScroll: { flex: 1, backgroundColor: colors.primary },
  loginScrollContent: {
    flexGrow: 1,
  },
  header: {
    backgroundColor: colors.primary,
    paddingVertical: spacing.xxxl,
    paddingHorizontal: spacing.xxxl,
    minHeight: 280,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  geo: {
    position: 'absolute',
    width: W * 1.6,
    height: 200,
    borderRadius: 2,
  },
  geo1: { backgroundColor: colors.primaryDark, opacity: 0.35, transform: [{ rotate: '-25deg' }], top: -80, left: -W * 0.5 },
  geo2: { backgroundColor: colors.primaryDark, opacity: 0.25, transform: [{ rotate: '20deg' }], top: 0, right: -W * 0.6 },
  geo3: { backgroundColor: colors.primaryDark, opacity: 0.2, transform: [{ rotate: '-35deg' }], bottom: -50, left: -W * 0.3 },
  geo4: { backgroundColor: colors.primaryDark, opacity: 0.15, transform: [{ rotate: '30deg' }], bottom: -30, right: -W * 0.4 },
  appName: { ...typography.h1, color: colors.white, fontSize: 36 },
  tagline: { ...typography.subtitle, color: colors.white, fontSize: 17, marginTop: spacing.md, opacity: 0.96 },
  /** Overlaps header; large radius reads clearly on all phones */
  card: {
    flexGrow: 1,
    backgroundColor: colors.card,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    marginTop: -28,
    paddingTop: spacing.xxl + 4,
    paddingHorizontal: spacing.xxxl,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 10,
  },
  welcome: { ...typography.h2, color: colors.text.primary },
  subWelcome: { ...typography.subtitle, color: colors.text.secondary, marginTop: spacing.sm, marginBottom: spacing.xxl },
  label: { ...typography.label, color: colors.text.label, marginBottom: spacing.sm },
  labelRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: spacing.xl, marginBottom: spacing.sm },
  forgot: { ...typography.link, color: colors.text.link },
  input: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBg,
    borderRadius: 12,
    paddingHorizontal: spacing.lg,
    height: 52,
  },
  inputIcon: { marginRight: spacing.md },
  inputField: { flex: 1, fontFamily: fontFamily.regular, fontSize: 16, color: colors.text.primary, paddingVertical: 0 },
  inputFieldPw: { paddingRight: spacing.sm },
  eyeBtn: { padding: spacing.sm },
  signInBtn: {
    backgroundColor: colors.primary,
    borderRadius: 27,
    height: 54,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: spacing.xxl,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  signInText: { ...typography.button, color: colors.white },
  footer: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginTop: 32, flexWrap: 'wrap' },
  /** Two footer lines: centred as a group, prompts + links left-aligned with each other */
  footerStack: { width: '100%', marginTop: 32, alignItems: 'center' },
  footerStackInner: { alignItems: 'flex-start' },
  footerRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: spacing.md },
  footerRowGap: { marginTop: spacing.lg },
  footerPrompt: { ...typography.caption, color: colors.text.label },
  footerLink: { ...typography.linkBold, color: colors.text.link },
  legal: { fontFamily: fontFamily.regular, fontSize: 11, color: colors.text.secondary, textAlign: 'center', marginTop: 24, paddingHorizontal: 24, opacity: 0.9 },
  forgotModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    paddingHorizontal: spacing.xxxl,
  },
  forgotModalCard: {
    backgroundColor: colors.card,
    borderRadius: 24,
    padding: spacing.xxl,
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 12,
  },
  forgotModalHeader: { flexDirection: 'row', justifyContent: 'flex-end', marginBottom: spacing.sm },
  forgotModalCloseBtn: { padding: spacing.sm, marginRight: -spacing.sm, marginTop: -spacing.sm },
  forgotModalIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(0,86,210,0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: spacing.lg,
  },
  forgotModalTitle: { ...typography.h2, fontSize: 22, color: colors.text.primary, textAlign: 'center', marginBottom: spacing.md },
  forgotModalBody: {
    ...typography.subtitle,
    fontSize: 15,
    lineHeight: 22,
    color: colors.text.secondary,
    textAlign: 'center',
    marginBottom: spacing.xl,
  },
  forgotModalHint: {
    fontFamily: fontFamily.regular,
    fontSize: 13,
    lineHeight: 19,
    color: colors.text.secondary,
    textAlign: 'center',
    marginBottom: spacing.lg,
    paddingHorizontal: spacing.sm,
  },
  forgotModalBtnSecondary: {
    marginTop: spacing.lg,
    paddingVertical: spacing.md,
    alignItems: 'center',
  },
  forgotModalBtnSecondaryText: { ...typography.link, color: colors.text.secondary, fontSize: 15 },
  forgotModalSuccessIcon: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#D1FAE5',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: spacing.lg,
  },
});

// ─── Create Account / Complete Profile Screen ───────────────────────────────
const profileBlue = '#0056D2';
export const createAccountScreenStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F5F6F8' },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.white,
    paddingHorizontal: spacing.xxxl,
    paddingVertical: spacing.lg,
    minHeight: 56,
  },
  /** Fixed-width slots so topBarTitle stays visually centred */
  topBarSide: {
    width: 48,
    minHeight: 48,
    justifyContent: 'center',
    alignItems: 'center',
  },
  topBarSideRight: {
    width: 48,
    minHeight: 48,
  },
  topBarTitle: {
    flex: 1,
    fontFamily: fontFamily.bold,
    fontSize: 20,
    lineHeight: 26,
    color: profileBlue,
    textAlign: 'center',
    ...Platform.select({
      android: { includeFontPadding: false, textAlignVertical: 'center' },
      default: {},
    }),
  },
  progressSection: { paddingHorizontal: spacing.xxxl, paddingTop: spacing.xl },
  stepRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  stepText: { fontFamily: fontFamily.bold, fontSize: 11, color: profileBlue, letterSpacing: 0.5 },
  stepLabel: { fontFamily: fontFamily.regular, fontSize: 13, color: colors.text.secondary },
  progressBarBg: {
    height: 4,
    backgroundColor: '#E5E7EB',
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressBarFill: { height: '100%', width: '25%', backgroundColor: profileBlue, borderRadius: 2 },
  content: { flex: 1, paddingHorizontal: spacing.xxxl, paddingTop: spacing.xxl },
  /** Spacing before Full Legal Name when company picker is shown (step 1 only) */
  step1CompanyPickerWrap: { marginBottom: spacing.xl },
  title: { fontFamily: fontFamily.bold, fontSize: 26, color: colors.text.primary },
  subtitle: { fontFamily: fontFamily.regular, fontSize: 15, color: colors.text.secondary, marginTop: spacing.md, marginBottom: spacing.xxl, lineHeight: 22 },
  photoSection: { alignItems: 'center', marginBottom: spacing.xxl },
  photoWrapper: { position: 'relative', marginBottom: 0 },
  photoCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#E5E7EB',
    overflow: 'hidden',
  },
  /** Fills {@link photoCircle}; clip comes from parent overflow. */
  photoCircleImage: {
    width: 120,
    height: 120,
  },
  photoAddBtn: {
    position: 'absolute',
    bottom: -4,
    right: -4,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: profileBlue,
    justifyContent: 'center',
    alignItems: 'center',
  },
  uploadLabel: { fontFamily: fontFamily.bold, fontSize: 15, color: profileBlue, marginTop: spacing.md },
  fieldLabel: { fontFamily: fontFamily.bold, fontSize: 14, color: profileBlue, marginBottom: spacing.sm },
  fieldHint: { fontFamily: fontFamily.regular, fontSize: 12, color: colors.text.secondary, marginBottom: spacing.sm },
  sexRow: { flexDirection: 'row', gap: spacing.lg },
  sexOption: {
    flex: 1,
    height: 52,
    borderRadius: 14,
    backgroundColor: colors.inputBg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sexOptionActive: { backgroundColor: profileBlue },
  sexOptionText: { fontFamily: fontFamily.regular, fontSize: 16, color: colors.text.primary },
  sexOptionTextActive: { color: colors.white, fontFamily: fontFamily.semiBold },
  daysRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  dayChip: {
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: 12,
    backgroundColor: colors.inputBg,
  },
  dayChipActive: { backgroundColor: profileBlue },
  dayChipText: { fontFamily: fontFamily.regular, fontSize: 14, color: colors.text.primary },
  dayChipTextActive: { color: colors.white, fontFamily: fontFamily.semiBold },
  /** Weekly schedule calendar (Step 2 availability) */
  scheduleCalendarCard: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: spacing.lg,
    marginTop: spacing.sm,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  scheduleCalendarTitle: {
    fontFamily: fontFamily.semiBold,
    fontSize: 15,
    color: colors.text.primary,
    marginBottom: spacing.xs,
  },
  scheduleCalendarHint: {
    fontFamily: fontFamily.regular,
    fontSize: 12,
    color: colors.text.secondary,
    marginBottom: spacing.md,
    lineHeight: 18,
  },
  scheduleWeekHeader: {
    flexDirection: 'row',
    marginBottom: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF2F6',
    paddingBottom: spacing.sm,
  },
  scheduleWeekHeaderCell: { flex: 1, alignItems: 'center' },
  scheduleWeekHeaderText: { fontFamily: fontFamily.semiBold, fontSize: 10, color: profileBlue, letterSpacing: 0.1 },
  scheduleSlotBlock: { marginTop: spacing.md },
  scheduleSlotLabelRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginBottom: spacing.sm },
  scheduleSlotLabelTextWrap: { flex: 1 },
  scheduleSlotTitle: { fontFamily: fontFamily.semiBold, fontSize: 13, color: colors.text.primary },
  scheduleSlotTime: { fontFamily: fontFamily.regular, fontSize: 12, color: colors.text.secondary },
  scheduleGridRow: { flexDirection: 'row', gap: 4 },
  scheduleCell: {
    flex: 1,
    minHeight: 40,
    borderRadius: 10,
    backgroundColor: colors.inputBg,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  scheduleCellActive: { backgroundColor: 'rgba(0,86,210,0.12)', borderColor: profileBlue },
  scheduleCellText: { fontFamily: fontFamily.medium, fontSize: 10, color: colors.text.secondary },
  scheduleCellTextActive: { color: profileBlue, fontFamily: fontFamily.semiBold },
  scheduleSummary: {
    marginTop: spacing.md,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: '#EEF2F6',
    fontFamily: fontFamily.regular,
    fontSize: 12,
    color: colors.text.secondary,
    lineHeight: 18,
  },
  idDocSection: { marginTop: spacing.xxl },
  idDocCard: {
    backgroundColor: colors.inputBg,
    borderRadius: 14,
    padding: spacing.lg,
    marginBottom: spacing.lg,
  },
  idDocCardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.md },
  idDocCardLabel: { fontFamily: fontFamily.semiBold, fontSize: 13, color: profileBlue },
  idDocRemoveBtn: { padding: spacing.xs },
  idDocUploadArea: {
    height: 120,
    borderRadius: 12,
    backgroundColor: colors.white,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#9CA3AF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  idDocUploadAreaFilled: { borderStyle: 'solid', borderColor: profileBlue },
  idDocUploadText: { fontFamily: fontFamily.regular, fontSize: 13, color: '#6B7280', marginTop: spacing.sm },
  idDocImage: { width: '100%', height: '100%', borderRadius: 10 },
  idDocAddBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: 12,
    backgroundColor: colors.inputBg,
    alignSelf: 'flex-start',
    marginTop: spacing.sm,
    gap: spacing.sm,
  },
  idDocAddBtnText: { fontFamily: fontFamily.semiBold, fontSize: 14, color: profileBlue },
  idDocMinHint: { fontFamily: fontFamily.regular, fontSize: 12, color: '#6B7280', marginTop: spacing.sm },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', padding: spacing.xxxl },
  modalContent: { backgroundColor: colors.white, borderRadius: 16, padding: spacing.lg },
  /** Date picker sheet — matches forgot-password modal + onboarding cards */
  datePickerModalContent: {
    backgroundColor: colors.white,
    borderRadius: 24,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xl,
    paddingBottom: spacing.md,
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 12,
  },
  datePickerModalTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 17,
    color: profileBlue,
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  datePickerWheelWrap: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: 12,
    overflow: 'hidden',
  },
  datePickerFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: spacing.xl,
    marginTop: spacing.md,
    paddingTop: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  modalOption: { paddingVertical: spacing.lg, borderBottomWidth: 1, borderBottomColor: '#E5E7EB' },
  modalOptionLast: { borderBottomWidth: 0 },
  modalOptionText: { fontFamily: fontFamily.regular, fontSize: 16, color: colors.text.primary },
  input: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBg,
    borderRadius: 14,
    paddingHorizontal: spacing.lg,
    height: 52,
  },
  inputField: { flex: 1, fontFamily: fontFamily.regular, fontSize: 16, color: colors.text.primary, paddingVertical: 0 },
  /** Room for trailing visibility toggle on password inputs */
  inputFieldPassword: { paddingRight: spacing.sm },
  passwordEyeBtn: { padding: spacing.sm, marginRight: -spacing.sm },
  inputMultiline: { minHeight: 80, alignItems: 'flex-start' },
  inputFieldMultiline: { minHeight: 76, textAlignVertical: 'top', paddingTop: spacing.lg },
  inputIconRight: { marginLeft: spacing.sm },
  saveBtn: {
    flexDirection: 'row',
    backgroundColor: profileBlue,
    borderRadius: 27,
    height: 54,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: spacing.xxl,
    marginBottom: spacing.xxxl,
    gap: spacing.sm,
  },
  saveBtnText: { fontFamily: fontFamily.bold, fontSize: 17, color: colors.white },
  saveBtnDisabled: { opacity: 0.55 },
  // Success modal
  successModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.xxxl,
  },
  successModalCard: {
    backgroundColor: colors.white,
    borderRadius: 24,
    padding: spacing.xxl,
    alignItems: 'center',
    width: '100%',
    maxWidth: 340,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 12,
  },
  successIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#D1FAE5',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  successModalTitle: { fontFamily: fontFamily.bold, fontSize: 22, color: colors.text.primary, textAlign: 'center', marginBottom: spacing.md },
  successModalMessage: { fontFamily: fontFamily.regular, fontSize: 15, color: colors.text.secondary, textAlign: 'center', lineHeight: 24, marginBottom: spacing.xxl },
  successModalBtn: {
    backgroundColor: profileBlue,
    borderRadius: 14,
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.xxl * 2,
    alignSelf: 'stretch',
    alignItems: 'center',
  },
  successModalBtnText: { fontFamily: fontFamily.semiBold, fontSize: 16, color: colors.white },
  termsAcceptRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: spacing.xxl,
    gap: spacing.md,
  },
  termsCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#D1D5DB',
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 2,
  },
  termsCheckboxChecked: {
    backgroundColor: profileBlue,
    borderColor: profileBlue,
  },
  termsAcceptTextWrap: { flex: 1 },
  termsAcceptText: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.text.primary,
    lineHeight: 22,
  },
  termsLink: {
    fontFamily: fontFamily.semiBold,
    fontSize: 14,
    color: profileBlue,
    textDecorationLine: 'underline',
  },
  termsModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    padding: spacing.xl,
  },
  termsModalCard: {
    backgroundColor: colors.white,
    borderRadius: 16,
    maxHeight: '88%',
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 12,
  },
  termsModalHeader: {
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xl,
    paddingBottom: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    alignItems: 'center',
  },
  termsModalIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(0,86,210,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  termsModalTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 20,
    color: colors.text.primary,
    textAlign: 'center',
  },
  termsModalUpdated: {
    fontFamily: fontFamily.regular,
    fontSize: 12,
    color: colors.text.secondary,
    marginTop: spacing.xs,
    textAlign: 'center',
  },
  termsModalScroll: { flexGrow: 0 },
  termsModalScrollContent: {
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.lg,
    paddingBottom: spacing.xl,
  },
  termsModalIntro: {
    fontFamily: fontFamily.regular,
    fontSize: 13,
    color: '#B45309',
    backgroundColor: '#FFFBEB',
    borderRadius: 10,
    padding: spacing.md,
    lineHeight: 20,
    marginBottom: spacing.lg,
  },
  termsModalSection: { marginBottom: spacing.lg },
  termsModalSectionTitle: {
    fontFamily: fontFamily.semiBold,
    fontSize: 14,
    color: profileBlue,
    marginBottom: spacing.xs,
  },
  termsModalSectionBody: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.text.secondary,
    lineHeight: 22,
  },
  termsModalCloseBtn: {
    backgroundColor: profileBlue,
    marginHorizontal: spacing.xl,
    marginBottom: spacing.xl,
    borderRadius: 14,
    paddingVertical: spacing.lg,
    alignItems: 'center',
  },
  termsModalCloseBtnText: { fontFamily: fontFamily.semiBold, fontSize: 16, color: colors.white },
  addressSuggestWrap: { position: 'relative', zIndex: 10, marginBottom: spacing.xs },
  addressSuggestDropdown: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: '100%',
    marginTop: spacing.sm,
    maxHeight: 220,
    backgroundColor: colors.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    zIndex: 100,
    elevation: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
  },
  addressSuggestScroll: { maxHeight: 220 },
  addressSuggestRow: {
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  addressSuggestRowLast: { borderBottomWidth: 0 },
  addressSuggestText: { fontFamily: fontFamily.regular, fontSize: 14, color: colors.text.primary, lineHeight: 20 },
  addressSuggestLoadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
  },
  addressSuggestLoadingText: { fontFamily: fontFamily.regular, fontSize: 13, color: colors.text.secondary },
  addressSuggestHint: {
    fontFamily: fontFamily.regular,
    fontSize: 11,
    color: colors.text.secondary,
    marginTop: spacing.xs,
    marginBottom: spacing.sm,
  },
});

// ─── Dashboard Screen ─────────────────────────────────────────────────────
export const dashboardStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F0F2F5' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.xxxl,
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
    backgroundColor: '#FFFFFF',
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 6,
  },
  profileAvatarWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#E8EEF5',
    padding: 2,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(0,61,122,0.15)',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
  },
  /** Matches `profileAvatarWrap` inner: 48 − 2×2 padding = 44, so the photo fills the ring */
  profileAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#E8EEF5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 22,
    color: colors.primary,
    marginLeft: spacing.lg,
    flex: 1,
    letterSpacing: -0.3,
  },
  bellBtn: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(0,61,122,0.08)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0,61,122,0.08)',
  },
  greetingCard: {
    marginTop: spacing.sm,
    marginBottom: spacing.lg,
    backgroundColor: colors.white,
    borderRadius: 20,
    padding: spacing.xl,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.03)',
  },
  greetingText: { fontFamily: fontFamily.regular, fontSize: 14, color: colors.text.secondary },
  userName: { fontFamily: fontFamily.bold, fontSize: 24, color: colors.text.primary, marginTop: spacing.xs },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: spacing.xxxl,
    paddingTop: spacing.xs,
    /** `paddingBottom` set in screen using floatingTabBarClearance(insets.bottom) */
    paddingBottom: spacing.xl,
  },
  scrollView: { flex: 1 },
  content: { flex: 1, paddingHorizontal: spacing.xxxl, paddingTop: spacing.sm },
  clockInCard: {
    borderRadius: 28,
    padding: spacing.xxl,
    alignItems: 'center',
    overflow: 'hidden',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 12,
  },
  /** Not clocked in — red-oriented unit */
  clockInCardOut: {
    backgroundColor: '#B91C1C',
    shadowColor: '#7F1D1D',
  },
  /** Clocked in — green-oriented unit */
  clockInCardIn: {
    backgroundColor: '#15803D',
    shadowColor: '#14532D',
  },
  clockInGeo: {
    position: 'absolute',
    width: W * 1.2,
    height: 180,
    borderRadius: 4,
  },
  clockInGeo1: { transform: [{ rotate: '-20deg' }], top: -60, right: -W * 0.4 },
  clockInGeo2: { transform: [{ rotate: '25deg' }], bottom: -40, left: -W * 0.5 },
  clockInGeo1Out: { backgroundColor: '#7F1D1D', opacity: 0.4 },
  clockInGeo2Out: { backgroundColor: '#450A0A', opacity: 0.28 },
  clockInGeo1In: { backgroundColor: '#166534', opacity: 0.45 },
  clockInGeo2In: { backgroundColor: '#052E16', opacity: 0.32 },
  statusLabel: { fontFamily: fontFamily.bold, fontSize: 11, letterSpacing: 1.2, color: 'rgba(255,255,255,0.88)', marginBottom: spacing.sm },
  statusRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginBottom: spacing.xl },
  statusDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: spacing.sm,
    borderWidth: 2,
  },
  statusDotOut: { backgroundColor: '#FECACA', borderColor: '#FEE2E2' },
  statusDotIn: { backgroundColor: '#86EFAC', borderColor: '#DCFCE7' },
  statusText: { fontFamily: fontFamily.bold, fontSize: 16, color: colors.white, letterSpacing: 0.2 },
  statusTextOut: { color: '#FEE2E2' },
  statusTextIn: { color: '#DCFCE7' },
  clockSinceText: {
    fontFamily: fontFamily.medium,
    fontSize: 13,
    color: '#BBF7D0',
    marginTop: spacing.xs,
    marginBottom: spacing.sm,
  },
  clockInBtn: {
    width: 150,
    height: 150,
    borderRadius: 75,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.xl,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  clockInBtnOut: {
    backgroundColor: '#FEF2F2',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.5)',
  },
  clockInBtnIn: {
    backgroundColor: '#ECFDF5',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.45)',
  },
  clockInBtnIcon: { marginBottom: spacing.sm },
  clockInBtnText: { fontFamily: fontFamily.bold, fontSize: 17 },
  clockInBtnTextOut: { color: '#991B1B' },
  clockInBtnTextIn: { color: '#166534' },
  shiftPill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.xxl,
    borderRadius: 24,
    gap: spacing.md,
    borderWidth: 1,
  },
  shiftPillOut: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderColor: 'rgba(255,255,255,0.22)',
  },
  shiftPillIn: {
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderColor: 'rgba(255,255,255,0.2)',
  },
  shiftPillText: { fontFamily: fontFamily.semiBold, fontSize: 15, color: colors.white },
  locationCard: {
    marginTop: spacing.xxl,
    backgroundColor: colors.white,
    borderRadius: 20,
    padding: spacing.xl,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.04)',
  },
  locationCardHeaderRow: {
    marginBottom: spacing.md,
    gap: spacing.sm,
  },
  locationHeading: {
    fontFamily: fontFamily.bold,
    fontSize: 17,
    color: colors.text.primary,
    lineHeight: 24,
  },
  locationShortName: {
    fontFamily: fontFamily.semiBold,
    fontSize: 16,
    color: colors.text.primary,
    lineHeight: 22,
    marginBottom: spacing.sm,
  },
  locationAddress: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.text.secondary,
    lineHeight: 22,
    width: '100%',
  },
  locationLoadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  locationLoadingText: { marginTop: 0 },
  locationCoordsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  locationCoordsText: { fontFamily: fontFamily.regular, fontSize: 12, color: colors.text.secondary },
  locationMapTouchable: {
    marginTop: spacing.lg,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#E5E7EB',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.06)',
  },
  locationMapImageWrap: { position: 'relative', width: '100%' },
  locationMapImage: { width: '100%', height: 200 },
  locationMapLoadingBox: {
    height: 200,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#EEF2F7',
  },
  locationMapLoadingHint: {
    fontFamily: fontFamily.regular,
    fontSize: 13,
    color: colors.text.secondary,
    marginTop: spacing.md,
  },
  locationMapPinOverlay: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginLeft: -18,
    marginTop: -36,
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  locationMapFallback: {
    height: 200,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#EEF2F7',
    paddingHorizontal: spacing.lg,
  },
  locationMapFallbackText: {
    fontFamily: fontFamily.medium,
    fontSize: 14,
    color: colors.text.secondary,
    textAlign: 'center',
    marginTop: spacing.sm,
  },
  locationMapKeyHint: {
    fontFamily: fontFamily.regular,
    fontSize: 13,
    color: colors.text.secondary,
    lineHeight: 20,
    marginTop: spacing.sm,
    paddingHorizontal: spacing.sm,
  },
  locationMapKeyHintBold: {
    fontFamily: fontFamily.semiBold,
    fontSize: 13,
    color: colors.text.primary,
  },
  locationMapHint: {
    fontFamily: fontFamily.regular,
    fontSize: 12,
    color: colors.text.secondary,
    marginTop: spacing.sm,
    textAlign: 'center',
  },
  locationMapHintBelow: {
    fontFamily: fontFamily.regular,
    fontSize: 12,
    color: colors.text.secondary,
    textAlign: 'center',
    paddingVertical: spacing.sm,
  },
  locationMapAttribution: {
    fontFamily: fontFamily.regular,
    fontSize: 11,
    color: '#9CA3AF',
    textAlign: 'center',
    marginTop: spacing.sm,
  },
  locationErrorText: { color: '#EF4444' },
  locationRefreshRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.lg,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  inZoneBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    maxWidth: '100%',
    backgroundColor: '#D1FAE5',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: 20,
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: 'rgba(5,150,105,0.2)',
  },
  outZoneBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    maxWidth: '100%',
    backgroundColor: '#FEF3C7',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: 20,
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: 'rgba(245,158,11,0.3)',
  },
  inZoneText: {
    fontFamily: fontFamily.semiBold,
    fontSize: 13,
    color: '#059669',
    flexShrink: 1,
  },
  outZoneText: {
    fontFamily: fontFamily.semiBold,
    fontSize: 13,
    color: '#D97706',
    flexShrink: 1,
  },
  locationRefreshBtn: { padding: spacing.sm },
  locationOpenSettingsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: colors.primary,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: 12,
    marginTop: spacing.md,
    gap: spacing.sm,
  },
  locationOpenSettingsText: { fontFamily: fontFamily.semiBold, fontSize: 14, color: colors.white },
});

const myProfileBlue = '#0056D2';
export const myProfileScreenStyles = StyleSheet.create({
  scrollOuter: {
    flex: 1,
    backgroundColor: '#E8ECF1',
  },
  heroCard: {
    backgroundColor: colors.white,
    borderRadius: 20,
    paddingVertical: spacing.xxl + 4,
    paddingHorizontal: spacing.xxl,
    alignItems: 'center',
    marginBottom: spacing.lg,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.05)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 4,
  },
  heroAvatarOuter: {
    padding: 4,
    borderRadius: 56,
    backgroundColor: 'rgba(0,86,210,0.12)',
    marginBottom: spacing.lg,
  },
  heroAvatar: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: '#EFF6FF',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(37,99,235,0.15)',
  },
  heroName: {
    fontFamily: fontFamily.bold,
    fontSize: 24,
    letterSpacing: -0.4,
    color: colors.text.primary,
    textAlign: 'center',
  },
  heroMeta: {
    fontFamily: fontFamily.medium,
    fontSize: 14,
    color: colors.text.secondary,
    marginTop: spacing.sm,
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: spacing.md,
  },
  heroBadge: {
    marginTop: spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: '#F0FDF4',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(5,150,105,0.2)',
  },
  heroBadgeText: {
    fontFamily: fontFamily.semiBold,
    fontSize: 12,
    color: '#047857',
    letterSpacing: 0.2,
  },
  syncBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    backgroundColor: '#FFFBEB',
    borderRadius: 12,
    padding: spacing.md,
    marginBottom: spacing.lg,
    borderWidth: 1,
    borderColor: 'rgba(217,119,6,0.28)',
  },
  syncBannerText: {
    flex: 1,
    fontFamily: fontFamily.medium,
    fontSize: 13,
    color: '#92400E',
    lineHeight: 18,
  },
  sectionCard: {
    backgroundColor: colors.white,
    borderRadius: 18,
    marginBottom: spacing.lg,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.05)',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  sectionCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xl,
    paddingBottom: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    backgroundColor: '#FAFBFC',
  },
  sectionIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(0,86,210,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.md,
  },
  sectionCardTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 17,
    color: colors.text.primary,
    letterSpacing: -0.2,
    flex: 1,
  },
  sectionCardBody: {
    paddingBottom: spacing.xs,
  },
  row: {
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.xl,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#EEF2F6',
  },
  rowLast: {
    borderBottomWidth: 0,
  },
  rowLabel: {
    fontFamily: fontFamily.semiBold,
    fontSize: 11,
    color: colors.text.label,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    marginBottom: spacing.sm,
  },
  rowValue: {
    fontFamily: fontFamily.medium,
    fontSize: 16,
    color: colors.text.primary,
    lineHeight: 24,
  },
  rowValueMuted: {
    fontFamily: fontFamily.regular,
    fontSize: 16,
    color: '#9CA3AF',
    fontStyle: 'italic',
    lineHeight: 24,
  },
  loadingCard: {
    alignSelf: 'center',
    marginTop: spacing.xxxl * 2,
    backgroundColor: colors.white,
    paddingVertical: spacing.xxl,
    paddingHorizontal: spacing.xxxl * 2,
    borderRadius: 18,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.06)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  loadingHint: {
    fontFamily: fontFamily.medium,
    fontSize: 14,
    color: colors.text.secondary,
    marginTop: spacing.lg,
  },
});

// ─── Tasks Screen ───────────────────────────────────────────────────────────
const taskBlue = '#004C99';
export const tasksStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F0F2F5' },
  scrollView: { flex: 1 },
  scrollContent: { paddingBottom: 120 },
  sectionTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 20,
    color: colors.text.primary,
    marginHorizontal: spacing.xxxl,
    marginTop: spacing.lg,
    letterSpacing: -0.3,
  },
  sectionSubtitle: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.text.secondary,
    marginHorizontal: spacing.xxxl,
    marginTop: spacing.xs,
    marginBottom: spacing.md,
    lineHeight: 20,
  },
  filterRow: {
    flexDirection: 'row',
    paddingHorizontal: spacing.xxxl,
    gap: spacing.sm,
    marginBottom: spacing.lg,
  },
  filterChip: {
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    borderRadius: 20,
    backgroundColor: colors.inputBg,
  },
  filterChipActive: {
    backgroundColor: taskBlue,
  },
  filterChipText: {
    fontFamily: fontFamily.semiBold,
    fontSize: 13,
    color: colors.text.secondary,
  },
  filterChipTextActive: {
    color: colors.white,
  },
  taskCard: {
    marginHorizontal: spacing.xxxl,
    marginBottom: spacing.md,
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: spacing.lg,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.04)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  taskCardDone: { opacity: 0.72 },
  priorityBar: { width: 4, borderRadius: 2, alignSelf: 'stretch', minHeight: 48 },
  priorityHigh: { backgroundColor: '#DC2626' },
  priorityMedium: { backgroundColor: '#D97706' },
  priorityLow: { backgroundColor: '#94A3B8' },
  taskBody: { flex: 1 },
  taskTitle: {
    fontFamily: fontFamily.semiBold,
    fontSize: 16,
    color: colors.text.primary,
    lineHeight: 22,
  },
  taskTitleDone: { textDecorationLine: 'line-through', color: colors.text.secondary },
  taskDesc: {
    fontFamily: fontFamily.regular,
    fontSize: 13,
    color: colors.text.secondary,
    marginTop: spacing.xs,
    lineHeight: 19,
  },
  taskMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacing.md,
    marginTop: spacing.md,
  },
  taskMetaItem: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  taskMetaText: { fontFamily: fontFamily.regular, fontSize: 12, color: colors.text.secondary },
  taskBadge: {
    alignSelf: 'flex-start',
    marginTop: spacing.sm,
    paddingVertical: 4,
    paddingHorizontal: spacing.sm,
    borderRadius: 8,
    backgroundColor: '#F1F5F9',
  },
  taskBadgeText: { fontFamily: fontFamily.semiBold, fontSize: 11, color: taskBlue, textTransform: 'uppercase' },
  checkBtn: { padding: spacing.xs, marginTop: -spacing.xs },
  emptyState: {
    marginHorizontal: spacing.xxxl,
    paddingVertical: spacing.xxl * 2,
    alignItems: 'center',
  },
  emptyTitle: {
    fontFamily: fontFamily.semiBold,
    fontSize: 16,
    color: colors.text.secondary,
    marginTop: spacing.lg,
    textAlign: 'center',
  },
  emptyHint: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.text.secondary,
    marginTop: spacing.sm,
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: spacing.xl,
  },
});

// ─── Chat / AI Assistant Screen ─────────────────────────────────────────────
const chatBlue = '#004C99';
export const chatStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F0F2F5' },
  keyboardFill: { flex: 1 },
  chatHeader: {
    paddingBottom: spacing.lg,
    alignItems: 'center',
  },
  headerTitleBlock: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.sm,
    minHeight: 48,
  },
  chatHeaderTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 20,
    color: colors.primary,
    letterSpacing: -0.3,
    textAlign: 'center',
    lineHeight: 26,
  },
  headerSubtitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginTop: 2,
  },
  headerSubtitle: {
    fontFamily: fontFamily.regular,
    fontSize: 12,
    color: colors.text.secondary,
    lineHeight: 16,
    textAlign: 'center',
  },
  headerSideSlot: {
    width: 48,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
  },
  onlineDotSmall: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#22C55E',
  },
  listHeaderWrap: {
    paddingTop: spacing.sm,
    marginBottom: spacing.lg,
  },
  heroCard: {
    backgroundColor: colors.white,
    borderRadius: 20,
    padding: spacing.xl,
    marginBottom: spacing.lg,
    borderWidth: 1,
    borderColor: 'rgba(0,76,153,0.12)',
    shadowColor: chatBlue,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
    alignItems: 'center',
  },
  heroIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(0,76,153,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  heroTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 18,
    color: colors.text.primary,
    marginBottom: spacing.sm,
    textAlign: 'center',
  },
  heroSubtitle: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.text.secondary,
    lineHeight: 21,
    textAlign: 'center',
    marginBottom: spacing.md,
  },
  heroStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    backgroundColor: 'rgba(34,197,94,0.08)',
    borderRadius: 20,
  },
  onlineDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#22C55E',
  },
  heroStatusText: {
    fontFamily: fontFamily.medium,
    fontSize: 12,
    color: '#15803D',
  },
  faqSectionLabel: {
    fontFamily: fontFamily.bold,
    fontSize: 11,
    letterSpacing: 0.8,
    color: colors.text.secondary,
    marginBottom: spacing.sm,
    textTransform: 'uppercase',
  },
  faqGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: spacing.sm,
    marginBottom: spacing.md,
  },
  faqChip: {
    width: '48%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
    borderRadius: 14,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    minHeight: 48,
  },
  faqChipIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: 'rgba(0,76,153,0.08)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  faqChipText: {
    flex: 1,
    fontFamily: fontFamily.medium,
    fontSize: 13,
    color: chatBlue,
  },
  messagesList: { flex: 1 },
  messagesContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
    flexGrow: 1,
  },
  listFooterWrap: {
    paddingTop: spacing.xs,
  },
  datePillWrap: {
    alignItems: 'center',
    marginVertical: spacing.md,
  },
  datePill: {
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.md,
    backgroundColor: 'rgba(0,0,0,0.06)',
    borderRadius: 12,
  },
  datePillText: {
    fontFamily: fontFamily.medium,
    fontSize: 11,
    color: colors.text.secondary,
    letterSpacing: 0.2,
  },
  messageRow: {
    flexDirection: 'row',
    marginBottom: spacing.md,
    maxWidth: '100%' as const,
    gap: spacing.sm,
  },
  messageRowAssistant: { alignSelf: 'flex-start', maxWidth: '88%' as const },
  messageRowUser: { alignSelf: 'flex-end', maxWidth: '82%' as const, flexDirection: 'row-reverse' },
  messageContentCol: { flexShrink: 1 },
  assistantAvatarSmall: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(0,76,153,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 4,
    flexShrink: 0,
  },
  bubbleAssistant: {
    backgroundColor: colors.white,
    borderRadius: 18,
    borderBottomLeftRadius: 6,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.06)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  bubbleUser: {
    backgroundColor: chatBlue,
    borderRadius: 18,
    borderBottomRightRadius: 6,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    shadowColor: chatBlue,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 3,
  },
  bubbleTextAssistant: {
    fontFamily: fontFamily.regular,
    fontSize: 15,
    color: colors.text.primary,
    lineHeight: 22,
  },
  bubbleTextUser: {
    fontFamily: fontFamily.regular,
    fontSize: 15,
    color: colors.white,
    lineHeight: 22,
  },
  bubbleMeta: {
    fontFamily: fontFamily.regular,
    fontSize: 11,
    color: colors.text.secondary,
    marginTop: spacing.xs,
    marginLeft: spacing.xs,
  },
  bubbleMetaUser: {
    textAlign: 'right',
    marginRight: spacing.xs,
    marginLeft: 0,
  },
  typingRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing.sm,
    marginBottom: spacing.sm,
    maxWidth: '88%' as const,
  },
  typingBubble: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: colors.white,
    borderRadius: 18,
    borderBottomLeftRadius: 6,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.06)',
  },
  typingDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#94A3B8',
  },
  chatBody: { flex: 1 },
  faqQuickBar: {
    backgroundColor: '#FAFBFC',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    paddingTop: spacing.sm,
    paddingBottom: spacing.xs,
  },
  faqQuickBarLabel: {
    fontFamily: fontFamily.semiBold,
    fontSize: 11,
    color: colors.text.secondary,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    marginBottom: spacing.sm,
    paddingHorizontal: spacing.lg,
  },
  faqQuickScroll: {
    paddingHorizontal: spacing.lg,
    gap: spacing.sm,
  },
  faqQuickChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: 20,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: 'rgba(0,76,153,0.18)',
    marginRight: spacing.sm,
  },
  faqQuickChipPressed: {
    backgroundColor: 'rgba(0,76,153,0.08)',
  },
  faqQuickChipText: {
    fontFamily: fontFamily.medium,
    fontSize: 13,
    color: chatBlue,
  },
  composerDock: {
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 4,
  },
  composerRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
    gap: spacing.sm,
  },
  inputShell: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-end',
    minHeight: 46,
    maxHeight: 120,
    backgroundColor: '#F3F4F6',
    borderRadius: 23,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingLeft: spacing.md,
    paddingRight: spacing.sm,
  },
  inputIcon: {
    marginBottom: 13,
    marginRight: spacing.xs,
  },
  inputField: {
    flex: 1,
    minHeight: 44,
    maxHeight: 108,
    fontFamily: fontFamily.regular,
    fontSize: 16,
    color: colors.text.primary,
    paddingVertical: Platform.OS === 'ios' ? spacing.md : spacing.sm,
    paddingRight: spacing.sm,
    textAlignVertical: 'center',
  },
  sendBtn: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: chatBlue,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sendBtnDisabled: { backgroundColor: '#CBD5E1' },
});
